package br.maua.cic303;

import java_cup.runtime.*;

parser code {:
    // Método chamado pelo CUP quando encontra um erro sintático
    public void syntax_error(Symbol cur_token) {
        throw new RuntimeException(
            "Erro Sintático na linha " +
            cur_token.left +
            ", coluna " +
            cur_token.right
        );
    }
:}

/* ========================================================================= */
/* TERMINAIS                                                                 */
/* ========================================================================= */

terminal IF, THEN, ELSE, WHILE;
terminal ASSIGN, LPAREN, RPAREN, LBRACE, RBRACE, SEMI;
terminal String ID, NUMBER;
terminal String ADD_OP, MUL_OP, REL_OP;

/* ========================================================================= */
/* NÃO TERMINAIS                                                             */
/* ========================================================================= */

non terminal program, stmt_list, stmt;
non terminal assign_stmt, if_stmt, while_stmt, block_stmt, null_stmt;

non terminal expr, rel_expr, add_expr, mul_expr, factor;

/* ========================================================================= */
/* GRAMÁTICA                                                                 */
/* ========================================================================= */

start with program;

/* ========================================================================= */
/* PROGRAMA                                                                  */
/* ========================================================================= */

program ::= stmt_list ;

/* ========================================================================= */
/* LISTA DE COMANDOS                                                         */
/* ========================================================================= */

stmt_list ::= stmt_list stmt
            |
            ;
/* ========================================================================= */
/* COMANDOS                                                                  */
/* ========================================================================= */

stmt ::= assign_stmt
       | if_stmt
       | while_stmt
       | block_stmt
       | null_stmt
       ;

/* ========================================================================= */
/* ATRIBUIÇÃO                                                                */
/* ========================================================================= */

assign_stmt ::= ID ASSIGN expr SEMI ;

/* ========================================================================= */
/* IF                                                                        */
/* ========================================================================= */

if_stmt ::= IF LPAREN expr RPAREN THEN block_stmt
          | IF LPAREN expr RPAREN THEN block_stmt ELSE block_stmt
          ;

/* ========================================================================= */
/* WHILE                                                                     */
/* ========================================================================= */

while_stmt ::= WHILE LPAREN expr RPAREN block_stmt ;

/* ========================================================================= */
/* BLOCO                                                                     */
/* ========================================================================= */

block_stmt ::= LBRACE stmt_list RBRACE ;

/* ========================================================================= */
/* COMANDO NULO                                                              */
/* ========================================================================= */

null_stmt ::= SEMI ;

/* ========================================================================= */
/* EXPRESSÕES                                                                */
/* ========================================================================= */

expr ::= rel_expr ;

rel_expr ::= rel_expr REL_OP add_expr
           | add_expr
           ;

add_expr ::= add_expr ADD_OP mul_expr
           | mul_expr
           ;

mul_expr ::= mul_expr MUL_OP factor
           | factor
           ;

factor ::= LPAREN expr RPAREN
         | NUMBER
         | ID
         ;
